const AUTH_REQUEST = "@authReducer/AUTH_REQUEST";
const AUTH_SUCCESS = "@authReducer/AUTH_SUCCESS";
const AUTH_FAILED = "@authReducer/AUTH_FAILED";
<<<<<<< HEAD

export { AUTH_FAILED, AUTH_REQUEST, AUTH_SUCCESS };
=======
const THONG_TIN_NGUOI_DUNG = "@authReducer/THONG_TIN_NGUOI_DUNG";

export { AUTH_FAILED, AUTH_REQUEST, AUTH_SUCCESS, THONG_TIN_NGUOI_DUNG };
>>>>>>> 446d025fb50ae36ca88537e21dade91d5d18b5c8
