const SLIDER_MOVIE_REQUEST = "@sliderMovieReducer/SLIDER_MOVIE_REQUEST";
const SLIDER_MOVIE_SUCCESS = "@sliderMovieReducer/SLIDER_MOVIE_SUCCESS";
const SLIDER_MOVIE_FAILED = "@sliderMovieReducer/SLIDER_MOVIE_FAILED";

export { SLIDER_MOVIE_REQUEST, SLIDER_MOVIE_SUCCESS, SLIDER_MOVIE_FAILED };
