const CINEMA_REQUEST = "@cinemaReducer/CINEMA_REQUEST";
const CINEMA_SUCCESS = "@cinemaReducer/CINEMA_SUCCESS";
const CINEMA_FAILED = "@cinemaReducer/CINEMA_FAILED";

export { CINEMA_SUCCESS, CINEMA_FAILED, CINEMA_REQUEST };
