const LIST_MOVIE_REQUEST = "@listMovieReducer/LIST_MOVIE_REQUEST";
const LIST_MOVIE_SUCCESS = "@listMovieReducer/LIST_MOVIE_SUCCESS";
const LIST_MOVIE_FAILED = "@listMovieReducer/LIST_MOVIE_FAILED";
const LIST_MOVIE_SHOWING = "@listMovieReducer/LIST_MOVIE_SHOWING";
const LIST_MOVIE_PREPARE_SHOWING =
  "@listMovieReducer/LIST_MOVIE_PREPARE_SHOWING";

export {
  LIST_MOVIE_REQUEST,
  LIST_MOVIE_SUCCESS,
  LIST_MOVIE_FAILED,
  LIST_MOVIE_SHOWING,
  LIST_MOVIE_PREPARE_SHOWING,
};
