const REGISTER_REQUEST = "@registerReducer/REGISTER_REQUEST";
const REGISTER_SUCCESS = "@registerReducer/REGISTER_SUCCESS";
const REGISTER_FAILED = "@registerReducer/REGISTER_FAILED";

export { REGISTER_REQUEST, REGISTER_SUCCESS, REGISTER_FAILED };
